# Generated by Django 4.0.1 on 2022-01-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0003_client_sale_detsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cant',
        ),
    ]
