# Generated by Django 4.0.1 on 2022-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0005_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='names',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
    ]
